name: 오류 신고
description: 오류 신고 폼 입니다.
title: "[버그]"
labels: 
  - bug
  - help wanted
  
body:
  - type: textarea
    id: bug_description
    attributes:
      label: 버그 설명
      description: 버그에 대한 구체적인 내용을 작성해 주세요.
      placeholder: "이곳에 버그 설명을 입력하세요."
    validations:
      required: true
      
  - type: textarea
    id: reproduction_steps
    attributes:
      label: 버그 생성 방법
      description: 버그를 재현할 수 있는 단계를 순서대로 작성해 주세요.
      placeholder: |
         1. Go to '...'
         2. Click on '...'
         3. Scroll down to '...'
         4. See error"
    validations:
      required: true
    
  - type: dropdown
    id: device_type
    attributes:
      label: 기기 유형
      description: 사용 중인 기기 유형을 선택하세요.
      options:
        - 모바일
        - 데스크톱
        - 노트북
    validations:
       required: true

  - type: input
    id: device_info
    attributes:
      label: 운영체제
      description: 사용중인 운영체제를 작성해 주세요
      placeholder: "예: Windows 10,11 / 안드로이드 / Mac / iPhone 그리고 Chrome, Edge 등등"
      validations:
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: 기타 사항
      description: 추가적으로 알리고 싶은 내용을 적어 주세요.
      placeholder: "이곳에 기타 사항을 입력하세요."

